export enum AuthenticationActionTypes {
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',

    TOKEN_REQUEST = 'TOKEN_REQUEST',
    TOKEN_SUCCESS = 'TOKEN_SUCCESS',
    TOKEN_FAILURE = 'TOKEN_FAILURE',

    USER_REQUEST = 'USER_REQUEST',
    USER_SUCCESS = 'USER_SUCCESS',
    USER_FAILURE = 'USER_FAILURE',

    LOGOUT_REQUEST = 'LOGOUT_REQUEST',

    CLEAN_STATE = 'CLEAN_STATE',
}
