export enum GeralTaskActionTypes {
    GERALTASK_REQUEST = 'GERALTASK_REQUEST',
    GERALTASK_SUCCESS = 'GERALTASK_SUCCESS',
    GERALTASK_FAILURE = 'GERALTASK_FAILURE',

    GERALTASKDONE_REQUEST = 'GERALTASKDONE_REQUEST',
    GERALTASKDONE_SUCCESS = 'GERALTASKDONE_SUCCESS',
    GERALTASKDONE_FAILURE = 'GERALTASKDONE_FAILURE',
    
    CLEAN_STATE = 'CLEAN_STATE',
}
